# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7a5270f65d9b9a52122ce38abad800fca4c0ddea7068d4147e056ad295ef6053bbbba2fda460c7c49277498a8e332a8441d8e28eed8ddd457b009512b193d99

test:
  secret_key_base: 3bb552cd34f002474275e16f8aa4e7c97470cdad8991e4b00eb8962c3edbbf1cce6504686657402f18b118757c1464aaa67473b2917ea1520a744127ca861b93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
